#!/usr/bin/env bash
# Builds the PHP 7 runtime (ZTS + pthreads + yaml) that GenisysPro / LiteCore 1.1.5 needs.
#
# Two modes:
#   1. PHP_TARBALL_URL is set -> just unpack a ready-made PocketMine-style PHP tarball
#   2. otherwise              -> compile PHP $PHP_VERSION from php.net sources
#
# pmmp/PHP-Binaries is deliberately NOT used any more: upstream deleted the old
# php-7.x branches ("Remote branch php-7.2 not found") and its current scripts
# build PHP 8 only, which old PocketMine forks cannot run.
set -euo pipefail

PREFIX="/opt/php"
WORK="${WORK:-/build}"
PHP_VERSION="${PHP_VERSION:-7.2.34}"
PHP_TARBALL_URL="${PHP_TARBALL_URL:-}"
PTHREADS_REF="${PTHREADS_REF:-v3.2.0}"
YAML_VERSION="${YAML_VERSION:-2.0.4}"
JOBS="${JOBS:-$(nproc)}"

log() { printf '\n==> %s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }

# fetch <output> <url> [fallback urls...]
fetch() {
	local out="$1"
	shift
	local url
	for url in "$@"; do
		log "downloading $url"
		if curl -fsSL --retry 3 --retry-delay 2 -o "$out" "$url"; then
			return 0
		fi
		warn "download failed: $url"
	done
	echo "no working download URL for $out" >&2
	return 1
}

install_prebuilt() {
	local php_bin root ext_dir
	mkdir -p /tmp/php "$PREFIX"
	fetch /tmp/php.tar.gz "$PHP_TARBALL_URL"
	tar -xzf /tmp/php.tar.gz -C /tmp/php
	php_bin="$(find /tmp/php -type f -name php -perm -u+x | head -n 1)"
	if [[ -z "$php_bin" ]]; then
		echo "the tarball contains no php binary" >&2
		exit 1
	fi
	root="$(dirname "$(dirname "$php_bin")")"
	cp -a "$root"/. "$PREFIX"/
	ext_dir="$(find "$PREFIX/lib" -maxdepth 4 -type d -name 'no-debug-*' | head -n 1 || true)"
	if [[ -n "$ext_dir" && -f "$PREFIX/bin/php.ini" ]]; then
		sed -i "s|^extension_dir=.*|extension_dir=\"$ext_dir\"|" "$PREFIX/bin/php.ini"
	fi
}

compile_php() {
	mkdir -p "$WORK/php-src"
	cd "$WORK"
	fetch php.tar.gz \
		"https://www.php.net/distributions/php-${PHP_VERSION}.tar.gz" \
		"https://museum.php.net/php7/php-${PHP_VERSION}.tar.gz" \
		"https://github.com/php/php-src/archive/refs/tags/php-${PHP_VERSION}.tar.gz"
	tar -xzf php.tar.gz -C "$WORK/php-src" --strip-components=1
	cd "$WORK/php-src"
	# release tarballs ship ./configure; git archives do not
	[[ -f configure ]] || ./buildconf --force
	export CFLAGS="-O2 -fcommon" CXXFLAGS="-O2 -fcommon"
	./configure \
		--prefix="$PREFIX" \
		--enable-maintainer-zts \
		--enable-cli \
		--disable-cgi \
		--disable-phpdbg \
		--disable-fpm \
		--without-pear \
		--enable-sockets \
		--enable-bcmath \
		--enable-mbstring \
		--with-openssl \
		--with-curl \
		--with-zlib \
		--with-gmp \
		--with-sqlite3 \
		--with-pdo-sqlite \
		--with-readline
	make "-j${JOBS}"
	make install
	"$PREFIX/bin/php" -v
}

# build_extension <source dir> [extra configure args...]
build_extension() {
	local dir="$1"
	shift
	cd "$dir"
	"$PREFIX/bin/phpize"
	./configure --with-php-config="$PREFIX/bin/php-config" "$@"
	make "-j${JOBS}"
	make install
}

compile_pthreads() {
	log "building pthreads ($PTHREADS_REF)"
	cd "$WORK"
	rm -rf pthreads
	git clone --quiet https://github.com/krakjoe/pthreads.git pthreads
	cd "$WORK/pthreads"
	if ! git checkout --quiet "$PTHREADS_REF"; then
		warn "ref $PTHREADS_REF not found, staying on the default branch"
	fi
	build_extension "$WORK/pthreads" --enable-pthreads
}

compile_yaml() {
	log "building yaml $YAML_VERSION"
	cd "$WORK"
	rm -rf yaml
	mkdir -p yaml
	fetch yaml.tgz "https://pecl.php.net/get/yaml-${YAML_VERSION}.tgz"
	tar -xzf yaml.tgz -C yaml --strip-components=1
	build_extension "$WORK/yaml" --with-yaml
}

write_ini() {
	local ext_dir
	ext_dir="$("$PREFIX/bin/php-config" --extension-dir)"
	cat > "$PREFIX/bin/php.ini" <<INI
; generated by build-php.sh for GenisysPro / LiteCore
extension_dir="$ext_dir"
extension=pthreads.so
extension=yaml.so
memory_limit=768M
phar.readonly=0
date.timezone=UTC
zend.assertions=-1
INI
}

main() {
	if [[ -n "$PHP_TARBALL_URL" ]]; then
		log "using a prebuilt PHP tarball"
		install_prebuilt
	else
		log "compiling PHP $PHP_VERSION (ZTS) + pthreads $PTHREADS_REF + yaml $YAML_VERSION"
		compile_php
		compile_pthreads
		compile_yaml
		write_ini
	fi

	log "verifying the runtime"
	PHPRC="$PREFIX/bin" "$PREFIX/bin/php" -v
	PHPRC="$PREFIX/bin" "$PREFIX/bin/php" -m > "$PREFIX/modules.txt"
	cat "$PREFIX/modules.txt"

	if ! grep -qix 'pthreads' "$PREFIX/modules.txt"; then
		echo "FATAL: pthreads is missing - GenisysPro / LiteCore will not start" >&2
		exit 1
	fi

	local ext
	for ext in yaml sockets curl openssl bcmath mbstring sqlite3 gmp zlib; do
		grep -qix "$ext" "$PREFIX/modules.txt" || warn "extension not loaded: $ext"
	done

	# keep the final image small
	rm -rf "$WORK" /tmp/php /tmp/php.tar.gz
	log "PHP is ready in $PREFIX"
}

main "$@"
